---
- name: Add homebrew cask tap repository
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - "{{ homebrew_cask_taps }}"
  when: homebrew_cask_taps

- name: Update homebrew cask
  homebrew: name=brew-cask state=latest

- name: Install cask packages
  homebrew_cask: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('installed') }}
  with_items:
    - "{{ homebrew_cask_packages }}"
  when: homebrew_cask_packages
  notify: reload dock
