---
- name: Add homebrew tap repository
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - "{{ homebrew_taps }}"
  when: homebrew_taps

- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install/Update brew packages
  homebrew: >
    name={{ item.name | default(item) }}
    state={{ item.state | default('latest') }}
    install_options={{
      item.install_options | default() | join(',')
      if item.install_options is not string
      else item.install_options
    }}
  with_items:
    - "{{ homebrew_packages }}"
  when: homebrew_packages
  notify: add-shell-zsh
